[providers]
node = "18"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build || echo 'No build step'"]

[start]
cmd = "node index.js"
